# Generated by Django 4.1.7 on 2023-02-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_sauce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pepperoni', models.BooleanField(blank=True, default=False)),
                ('chicken', models.BooleanField(blank=True, default=False)),
                ('ham', models.BooleanField(blank=True, default=False)),
                ('pineapple', models.BooleanField(blank=True, default=False)),
                ('peppers', models.BooleanField(blank=True, default=False)),
                ('mushrooms', models.BooleanField(blank=True, default=False)),
                ('onions', models.BooleanField(blank=True, default=False)),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrdering.cheese')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrdering.crust')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrdering.sauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaOrdering.size')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('address3', models.CharField(max_length=1024, verbose_name='Address line 3')),
                ('card_no', models.IntegerField(verbose_name='Credit card number')),
                ('card_exp_date_month', models.IntegerField()),
                ('card_exp_date_year', models.IntegerField()),
                ('card_ccv', models.IntegerField()),
                ('pizza', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='PizzaOrdering.pizza')),
            ],
        ),
    ]
